### ISSUE TITLE
sleep

### ISSUE THREAD

**Issue by shubham49m** [pbssubhash/AbuseIPDBChecker#1]
please implement time.sleep(5) in a script to not get block.

**Comment by shubham49m** [comment]
python3 abuse.py --format=csv --file=ip.txt > ip.csv

**Comment by pbssubhash** [comment]
Hey, 

Please check https://github.com/pbssubhash/AbuseIPDBChecker/blob/master/AbuseIPDBChecker.py#L16. It's implemented.

**Comment by shubham49m** [comment]
thanks bro! :D xD
